[versions]
agp = "8.3.2"
kotlin = "1.9.0"
activity = "1.8.2"
appcompat = "1.6.1"
viewpager2 = "1.0.0"
espressoCore = "3.5.1"
testCore = "1.5.0"
testJunit = "1.1.5"

[libraries]
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "testCore" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "testJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

